name: Aurelia
version: "${project.version}"
main: io.skiftstar.aurelia.Aurelia
api-version: "1.20"
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true